In [1]:
import pandas as pd
import numpy as np

## Kardec data read

In [2]:
def matriz(num_colunas, array1):
    """
    Gera uma matriz sequencial a partir de um array, com o número de colunas especificado.

    Args:
        array (list ou np.ndarray): Array de entrada.
        num_colunas (int): Número de colunas desejado na matriz.

    Returns:
        np.ndarray: Matriz sequencial.
    """
    if num_colunas > len(array1):
        raise ValueError("O número de colunas não pode ser maior que o tamanho do array.")

    # Número de linhas na matriz
    num_linhas = len(array1) - num_colunas + 1

    # Criando a matriz sequencial
    matriz = np.array([array1[i:i + num_colunas] for i in range(num_linhas)])
    return matriz

In [3]:
array1 = np.arange(600)
array1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [4]:
matriz1 = matriz(60, array1)
matriz1

array([[  0,   1,   2, ...,  57,  58,  59],
       [  1,   2,   3, ...,  58,  59,  60],
       [  2,   3,   4, ...,  59,  60,  61],
       ...,
       [538, 539, 540, ..., 595, 596, 597],
       [539, 540, 541, ..., 596, 597, 598],
       [540, 541, 542, ..., 597, 598, 599]])

In [5]:
data1 = pd.read_csv('/home/darkcover/Documentos/Out/dados/Saidas/FUNCOES/DOUBLE - 17_09_s1.csv')
data1.columns

Index(['n', 'Entrada', 'Odd', 'P60', 'P120', 'P180', 'P240', 'P300', 'P360',
       'P420', 'P480', 'P540', 'P600', 'P660', 'P720', 'P780', 'P840', 'P900',
       'P960', 'P1020', 'P1080', 'P1140', 'P1200', 'P1260', 'P1320', 'P1380',
       'P1440', 'P1500', 'P1560', 'P1620', 'P1680', 'P1740', 'P1800', 'P1860',
       'P1920', 'P1980', 'P1200.1', 'Media Movel', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Acertos 60',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66',
       'Unnamed: 67', 'Unnamed: 68', 'Acertos Geral', 'Média Global',
       'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74',
       'Unnamed:

In [6]:
array2 = data1['Entrada']
array2

0        11,6
1        2,02
2        2,02
3        1,54
4         2,2
        ...  
1667        1
1668     4,34
1669    19,98
1670     2,52
1671     10,2
Name: Entrada, Length: 1672, dtype: object

In [7]:
array3 = []
array4 = []
for i in range(600):
    odd = array2[i].replace(',','.')
    if float(odd) >= 6:
        odd = 6
    array3.append(float(odd))
    if float(odd) >= 3:
        corte1 = 1
    else:
        corte1 = 0
    array4.append(corte1)

array3

[6.0,
 2.02,
 2.02,
 1.54,
 2.2,
 1.51,
 6.0,
 3.89,
 1.02,
 1.48,
 1.25,
 1.07,
 1.93,
 4.33,
 3.59,
 3.26,
 1.83,
 1.6,
 2.07,
 6.0,
 1.21,
 5.46,
 3.81,
 1.3,
 1.95,
 1.04,
 1.28,
 1.03,
 1.05,
 3.39,
 1.05,
 2.59,
 2.53,
 6.0,
 1.34,
 1.56,
 1.0,
 1.22,
 1.05,
 6.0,
 2.54,
 2.44,
 2.34,
 6.0,
 6.0,
 1.44,
 1.63,
 2.57,
 1.73,
 1.22,
 1.34,
 1.33,
 1.0,
 2.87,
 2.28,
 6.0,
 1.0,
 1.73,
 1.05,
 1.52,
 5.63,
 4.44,
 3.91,
 6.0,
 2.44,
 1.43,
 1.83,
 1.31,
 1.61,
 1.73,
 1.4,
 2.12,
 1.49,
 5.97,
 1.12,
 1.55,
 1.4,
 2.62,
 2.87,
 1.77,
 1.02,
 1.28,
 6.0,
 2.18,
 1.99,
 4.71,
 1.01,
 1.15,
 1.41,
 6.0,
 1.92,
 1.2,
 1.0,
 2.35,
 6.0,
 1.24,
 4.81,
 1.0,
 1.27,
 1.49,
 1.94,
 1.98,
 5.93,
 1.76,
 1.9,
 1.71,
 6.0,
 6.0,
 6.0,
 2.03,
 1.14,
 1.29,
 6.0,
 1.0,
 2.21,
 3.09,
 1.49,
 3.34,
 1.04,
 2.26,
 1.21,
 1.26,
 1.01,
 1.21,
 3.08,
 2.7,
 2.3,
 2.51,
 1.17,
 1.02,
 4.1,
 1.17,
 1.61,
 6.0,
 2.74,
 1.67,
 5.5,
 1.41,
 1.13,
 1.0,
 1.49,
 2.3,
 1.31,
 1.18,
 6.0,
 6.0,
 3.16,
 4.08,
 6

In [8]:
matriz2 = matriz(60, array3)
matriz2

array([[6.  , 2.02, 2.02, ..., 1.73, 1.05, 1.52],
       [2.02, 2.02, 1.54, ..., 1.05, 1.52, 5.63],
       [2.02, 1.54, 2.2 , ..., 1.52, 5.63, 4.44],
       ...,
       [2.12, 1.33, 1.6 , ..., 2.49, 2.24, 6.  ],
       [1.33, 1.6 , 1.06, ..., 2.24, 6.  , 3.22],
       [1.6 , 1.06, 1.05, ..., 6.  , 3.22, 1.49]])

In [9]:
matriz3 = matriz(60,array4)
matriz3

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 1, 0]])

In [10]:
array5 = []
for i in range(len(array4) - 1):
    if i >= 59:
        order = sum(array4[i - 59: i])
        array5.append(order)
array5

[15,
 14,
 15,
 16,
 17,
 18,
 18,
 17,
 16,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 14,
 14,
 14,
 14,
 13,
 13,
 12,
 11,
 12,
 12,
 12,
 13,
 13,
 13,
 12,
 13,
 13,
 13,
 12,
 12,
 13,
 13,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 12,
 12,
 12,
 13,
 14,
 15,
 15,
 15,
 15,
 16,
 16,
 15,
 16,
 16,
 17,
 17,
 16,
 15,
 14,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 14,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 15,
 15,
 16,
 17,
 18,
 18,
 19,
 20,
 20,
 21,
 21,
 21,
 20,
 21,
 21,
 21,
 22,
 22,
 21,
 21,
 21,
 21,
 20,
 20,
 20,
 21,
 22,
 23,
 23,
 23,
 24,
 24,
 25,
 25,
 25,
 25,
 26,
 27,
 27,
 28,
 27,
 27,
 27,
 27,
 28,
 28,
 27,
 28,
 28,
 27,
 28,
 28,
 27,
 27,
 28,
 28,
 29,
 30,
 30,
 30,
 29,
 28,
 27,
 26,
 25,
 25,
 24,
 25,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 24,
 24,
 23,
 22,
 21,
 20,
 20,
 19,
 18,
 17,
 16,
 16,
 16,
 16,
 15,
 16,
 15,
 16,
 16,
 16,
 16,
 15,
 16,
 16,
 15,
 15,
 15,
 14,
 15,
 16,
 16,
 15,
 16,


In [11]:
matriz4 = matriz(60, array5)
matriz4

array([[15, 14, 15, ..., 16, 16, 17],
       [14, 15, 16, ..., 16, 17, 17],
       [15, 16, 17, ..., 17, 17, 16],
       ...,
       [14, 14, 13, ..., 10, 11, 11],
       [14, 13, 13, ..., 11, 11, 11],
       [13, 13, 13, ..., 11, 11, 12]])

## Indicador de futura função:
import numpy as np

def calculate_means(array4):
    """
    Calcula a média dos elementos de array4 em janelas deslizantes de 59 elementos.

    Args:
        array4 (list): Lista de inteiros (0 ou 1).

    Returns:
        list: Lista com a média dos elementos em janelas de 59 elementos.
    """
    array6 = []
    array7 = []
    for i in range(len(array4) - 1):
        array6.append(array4[i])
        if i >= 59:
            order = float(np.mean(array6))
            array7.append(order)
    return array7

# Exemplo de uso:
# array4 = [0, 1, 0, 1, ...]  # Supondo que array4 tenha elementos suficientes
# array7 = calculate_means(array4)

# Teste unitário básico
def test_calculate_means():
    array4 = [1] * 60  # Lista com 60 elementos, todos iguais a 1
    expected_output = [1.0]  # A média dos primeiros 59 elementos é 1.0
    array7 = calculate_means(array4)
    assert array7 == expected_output, "Teste falhou!"

# Executar o teste
test_calculate_means()

In [12]:
array6 = []
array7 = []
for i in range(len(array4) - 1):
    array6.append(array4[i])
    if i >= 59:
        order = float(np.mean(array6))
        array7.append(order)

array7


[0.25,
 0.26229508196721313,
 0.27419354838709675,
 0.2857142857142857,
 0.296875,
 0.2923076923076923,
 0.2878787878787879,
 0.2835820895522388,
 0.27941176470588236,
 0.2753623188405797,
 0.2714285714285714,
 0.2676056338028169,
 0.2638888888888889,
 0.2602739726027397,
 0.2702702702702703,
 0.26666666666666666,
 0.2631578947368421,
 0.2597402597402597,
 0.2564102564102564,
 0.25316455696202533,
 0.25,
 0.24691358024691357,
 0.24390243902439024,
 0.25301204819277107,
 0.25,
 0.24705882352941178,
 0.2558139534883721,
 0.25287356321839083,
 0.25,
 0.24719101123595505,
 0.25555555555555554,
 0.25274725274725274,
 0.25,
 0.24731182795698925,
 0.24468085106382978,
 0.25263157894736843,
 0.25,
 0.25773195876288657,
 0.25510204081632654,
 0.25252525252525254,
 0.25,
 0.24752475247524752,
 0.24509803921568626,
 0.2524271844660194,
 0.25,
 0.24761904761904763,
 0.24528301886792453,
 0.2523364485981308,
 0.25925925925925924,
 0.26605504587155965,
 0.2636363636363636,
 0.26126126126126126,
 0.2

In [13]:
matriz5 = matriz(60, array7)
matriz5

array([[0.25      , 0.26229508, 0.27419355, ..., 0.26495726, 0.27118644,
        0.26890756],
       [0.26229508, 0.27419355, 0.28571429, ..., 0.27118644, 0.26890756,
        0.26666667],
       [0.27419355, 0.28571429, 0.296875  , ..., 0.26890756, 0.26666667,
        0.26446281],
       ...,
       [0.30855019, 0.30797774, 0.30740741, ..., 0.29747899, 0.29697987,
        0.29648241],
       [0.30797774, 0.30740741, 0.30683919, ..., 0.29697987, 0.29648241,
        0.29765886],
       [0.30740741, 0.30683919, 0.30627306, ..., 0.29648241, 0.29765886,
        0.29883139]])

In [14]:
matriz2.shape, matriz3.shape, matriz4.shape, matriz5.shape

((541, 60), (541, 60), (481, 60), (481, 60))

In [15]:
order = matriz2.shape[0] - matriz4.shape[0]
order

60

In [18]:
matrizfloat = matriz2[60:,:]
matrizint = matriz3[60:,:]

In [19]:
matrizfloat.shape, matrizint.shape, matriz4.shape, matriz5.shape

((481, 60), (481, 60), (481, 60), (481, 60))

In [20]:
len(array2), len(array3), len(array4), len(array5), len(array7)

(1672, 600, 600, 540, 540)

In [21]:
x1 = matrizfloat[:,:(matrizfloat.shape[1] - 1)]
x2 = matriz4[:,:(matriz4.shape[1] - 1)]
x3 = matriz5[:,:(matriz5.shape[1] - 1)]

y = matrizint[:,-1]

In [22]:
x1.shape, x2.shape, x3.shape, y.shape

((481, 59), (481, 59), (481, 59), (481,))

In [35]:
# Empilhar as matrizes para ter um eixo extra (60, 8, 3)
X_stack = np.stack([x1, x2, x3], axis=2)  # Formato (60, 8, 3)

# Reorganizar para intercalar coluna por coluna
X_intercalado = X_stack.reshape(59, -1)  # Agora está no formato (60, 24)

print(X_intercalado.shape)  # Saída: (60, 24)

(59, 1443)


In [29]:
X_intercalado, y

(array([[ 5.63      , 15.        ,  0.25      , ...,  0.25641026,
          1.77      , 14.        ],
        [ 0.25316456,  1.02      , 13.        , ..., 14.        ,
          0.25510204,  1.49      ],
        [14.        ,  0.25252525,  1.94      , ...,  1.04      ,
         16.        ,  0.27118644],
        ...,
        [ 1.6       , 13.        ,  0.30740741, ...,  0.30107527,
          1.7       , 13.        ],
        [ 0.30053667,  6.        , 13.        , ..., 12.        ,
          0.29757785,  1.12      ],
        [11.        ,  0.2970639 ,  2.36      , ...,  3.22      ,
         11.        ,  0.29765886]]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
   

In [57]:
import pandas as pd
import numpy as np

# Garantir que são arrays NumPy
x1, x2, x3 = np.array(x1), np.array(x2), np.array(x3)

# Criar DataFrames separando cada coluna
df_x1 = pd.DataFrame(x1, columns=[f'X1_{i}' for i in range(x1.shape[1])])
df_x2 = pd.DataFrame(x2, columns=[f'X2_{i}' for i in range(x2.shape[1])])
df_x3 = pd.DataFrame(x3, columns=[f'X3_{i}' for i in range(x3.shape[1])])

# Juntar todas as colunas
X_df = pd.concat([df_x1, df_x2, df_x3], axis=1)

# Transformar para valores NumPy
X = X_df.values


In [58]:
print(X.shape, y.shape)  # X deve ter o mesmo número de linhas de y


(481, 177) (481,)


In [59]:
X

array([[5.63      , 4.44      , 3.91      , ..., 0.26724138, 0.26495726,
        0.27118644],
       [4.44      , 3.91      , 6.        , ..., 0.26495726, 0.27118644,
        0.26890756],
       [3.91      , 6.        , 2.44      , ..., 0.27118644, 0.26890756,
        0.26666667],
       ...,
       [2.12      , 1.33      , 1.6       , ..., 0.2962963 , 0.29747899,
        0.29697987],
       [1.33      , 1.6       , 1.06      , ..., 0.29747899, 0.29697987,
        0.29648241],
       [1.6       , 1.06      , 1.05      , ..., 0.29697987, 0.29648241,
        0.29765886]])

In [34]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

# Dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo XGBoost
model = xgb.XGBClassifier(
    objective='multi:softmax',  # Classificação multiclasse
    num_class=2,  # Número de categorias na saída
    eval_metric='mlogloss',
    learning_rate=0.01,
    n_estimators=100,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

# Fazer previsões
y_pred = model.predict(X_test)

# Avaliar o modelo
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f'Acurácia do modelo: {accuracy:.4f}')
print(f'F1-Score do modelo: {f1:.4f}')


Acurácia do modelo: 0.6701
F1-Score do modelo: 0.5631


In [37]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.metrics import Precision, Recall
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
import tensorflow_addons as tfa
#activation = tf.keras.activations.elu
from tensorflow.keras.optimizers import Nadam

import skfuzzy as fuzz

# Libs
import time
import warnings

2025-03-04 17:30:25.719648: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-04 17:30:25.836661: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-04 17:30:25.942496: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741123826.052265   14195 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741123826.077160   14195 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-04 17:30:26.317913: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [63]:
def reden(array1, array3, m, n):
    """
    Função para treinar uma rede neural usando as entradas e saídas fornecidas.

    Args:
        array1 (numpy.array): Saídas (rótulos) binárias (0 ou 1).
        array3 (numpy.array): Entradas preditoras.
        m (int): Número de amostras.
        n (int): Número de características por amostra.

    Returns:
        keras.Model: Modelo treinado.
    """
    # Dividindo os dados em treino e teste
    X = np.array(array3)
    y = np.array(array1)
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # Ajustando dimensões para entrada no modelo
    x_train = np.expand_dims(x_train, -1).astype("float32")
    x_test = np.expand_dims(x_test, -1).astype("float32")
    input_shape = (n , 1)  # Formato esperado de entrada

    # Convertendo saídas para categóricas
    num_classes = 2
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    # Definição do modelo
    model = keras.Sequential([
        keras.Input(shape=input_shape),
        layers.Flatten(),
        layers.Dense(128, activation="relu", use_bias=True),
        layers.Dropout(0.5),
        layers.Dense(64, activation="relu", use_bias=True),
        layers.Dense(32, activation=tf.keras.activations.swish, use_bias=True),
        layers.Dense(num_classes, activation="softmax"),
    ])

    model.compile(
        loss=tfa.losses.SigmoidFocalCrossEntropy(alpha=0.7, gamma=2.0),
        #loss=tfa.losses.SigmoidFocalCrossEntropy(alpha=0.25, gamma=2.0), #testa loss = tfa.losses.SigmoidFocalCrossEntropy(alpha=0.25, gamma=2.0)
        optimizer=tf.keras.optimizers.AdamW(learning_rate=0.001, weight_decay=1e-4),
        metrics=['accuracy', Precision(name="precision"), Recall(name="recall")]
    )

    # Treinamento
    batch_size = 2**10
    epochs = 50
    model.fit(
        x_train, y_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_split=0.2,
    )

    # Avaliação
    score = model.evaluate(x_test, y_test, verbose=0)
    print(f"Test loss: {score[0]:.4f}")
    print(f"Test accuracy: {score[1]:.4f}")
    print(f"Precision: {score[2]:.4f}")
    print(f"Recall: {score[3]:.4f}")

    return model


In [51]:
y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,

In [60]:
X.shape

(481, 177)

In [43]:
np.unique(y)

array([0, 1])

In [64]:

model = reden(y, X, X.shape[0], X.shape[1])

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5075 - loss: 2.7479 - precision: 0.5075 - recall: 0.5075 - val_accuracy: 0.7059 - val_loss: 3.2853 - val_precision: 0.7059 - val_recall: 0.7059
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6343 - loss: 2.8283 - precision: 0.6343 - recall: 0.6343 - val_accuracy: 0.7059 - val_loss: 2.7800 - val_precision: 0.7059 - val_recall: 0.7059
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.6679 - loss: 2.3336 - precision: 0.6679 - recall: 0.6679 - val_accuracy: 0.7059 - val_loss: 1.3745 - val_precision: 0.7059 - val_recall: 0.7059
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step - accuracy: 0.5784 - loss: 1.9375 - precision: 0.5784 - recall: 0.5784 - val_accuracy: 0.7353 - val_loss: 0.3892 - val_precision: 0.7353 - val_recall: 0.7353
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5448 - loss: 1.9259 - precision: 0.5448 - recall: 0.5448 - val_accuracy: 0.5882 - val_loss: 0.3475 - val_prec

In [62]:
X.shape, y.shape

((481, 177), (481,))