In [1]:
import pandas as pd
import numpy as np

## Oz data read

In [3]:
def matriz(num_linhas, array):
    """
    Transforma um array unidimensional em uma matriz organizada por colunas.
    
    Args:
        array (list ou np.array): Lista de números a serem organizados.
        num_linhas (int): Número de linhas desejadas na matriz.

    Returns:
        np.array: Matriz ordenada.
    """
    
    # Reshape para matriz (por linha) e depois transpõe para organizar por colunas
    matriz = np.array(array).reshape(-1, num_linhas).T
    
    return matriz # Retorna como lista para melhor legibilidade

In [4]:
array1 = np.arange(600)
array1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [87]:
matriz1 = matriz(60, array1)
matriz1

array([[  0,  60, 120, 180, 240, 300, 360, 420, 480, 540],
       [  1,  61, 121, 181, 241, 301, 361, 421, 481, 541],
       [  2,  62, 122, 182, 242, 302, 362, 422, 482, 542],
       [  3,  63, 123, 183, 243, 303, 363, 423, 483, 543],
       [  4,  64, 124, 184, 244, 304, 364, 424, 484, 544],
       [  5,  65, 125, 185, 245, 305, 365, 425, 485, 545],
       [  6,  66, 126, 186, 246, 306, 366, 426, 486, 546],
       [  7,  67, 127, 187, 247, 307, 367, 427, 487, 547],
       [  8,  68, 128, 188, 248, 308, 368, 428, 488, 548],
       [  9,  69, 129, 189, 249, 309, 369, 429, 489, 549],
       [ 10,  70, 130, 190, 250, 310, 370, 430, 490, 550],
       [ 11,  71, 131, 191, 251, 311, 371, 431, 491, 551],
       [ 12,  72, 132, 192, 252, 312, 372, 432, 492, 552],
       [ 13,  73, 133, 193, 253, 313, 373, 433, 493, 553],
       [ 14,  74, 134, 194, 254, 314, 374, 434, 494, 554],
       [ 15,  75, 135, 195, 255, 315, 375, 435, 495, 555],
       [ 16,  76, 136, 196, 256, 316, 376, 436, 496, 556

In [7]:
data1 = pd.read_csv('/home/darkcover/Documentos/Out/dados/Saidas/FUNCOES/DOUBLE - 17_09_s1.csv')
data1.columns

Index(['n', 'Entrada', 'Odd', 'P60', 'P120', 'P180', 'P240', 'P300', 'P360',
       'P420', 'P480', 'P540', 'P600', 'P660', 'P720', 'P780', 'P840', 'P900',
       'P960', 'P1020', 'P1080', 'P1140', 'P1200', 'P1260', 'P1320', 'P1380',
       'P1440', 'P1500', 'P1560', 'P1620', 'P1680', 'P1740', 'P1800', 'P1860',
       'P1920', 'P1980', 'P1200.1', 'Media Movel', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Acertos 60',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66',
       'Unnamed: 67', 'Unnamed: 68', 'Acertos Geral', 'Média Global',
       'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74',
       'Unnamed:

In [8]:
array2 = data1['Entrada']
array2

0        11,6
1        2,02
2        2,02
3        1,54
4         2,2
        ...  
1667        1
1668     4,34
1669    19,98
1670     2,52
1671     10,2
Name: Entrada, Length: 1672, dtype: object

In [18]:
array3 = []
array4 = []
for i in range(600):
    odd = array2[i].replace(',','.')
    if float(odd) >= 6:
        odd = 6
    array3.append(float(odd))
    if float(odd) >= 3:
        corte1 = 1
    else:
        corte1 = 0
    array4.append(corte1)

array3

[6.0,
 2.02,
 2.02,
 1.54,
 2.2,
 1.51,
 6.0,
 3.89,
 1.02,
 1.48,
 1.25,
 1.07,
 1.93,
 4.33,
 3.59,
 3.26,
 1.83,
 1.6,
 2.07,
 6.0,
 1.21,
 5.46,
 3.81,
 1.3,
 1.95,
 1.04,
 1.28,
 1.03,
 1.05,
 3.39,
 1.05,
 2.59,
 2.53,
 6.0,
 1.34,
 1.56,
 1.0,
 1.22,
 1.05,
 6.0,
 2.54,
 2.44,
 2.34,
 6.0,
 6.0,
 1.44,
 1.63,
 2.57,
 1.73,
 1.22,
 1.34,
 1.33,
 1.0,
 2.87,
 2.28,
 6.0,
 1.0,
 1.73,
 1.05,
 1.52,
 5.63,
 4.44,
 3.91,
 6.0,
 2.44,
 1.43,
 1.83,
 1.31,
 1.61,
 1.73,
 1.4,
 2.12,
 1.49,
 5.97,
 1.12,
 1.55,
 1.4,
 2.62,
 2.87,
 1.77,
 1.02,
 1.28,
 6.0,
 2.18,
 1.99,
 4.71,
 1.01,
 1.15,
 1.41,
 6.0,
 1.92,
 1.2,
 1.0,
 2.35,
 6.0,
 1.24,
 4.81,
 1.0,
 1.27,
 1.49,
 1.94,
 1.98,
 5.93,
 1.76,
 1.9,
 1.71,
 6.0,
 6.0,
 6.0,
 2.03,
 1.14,
 1.29,
 6.0,
 1.0,
 2.21,
 3.09,
 1.49,
 3.34,
 1.04,
 2.26,
 1.21,
 1.26,
 1.01,
 1.21,
 3.08,
 2.7,
 2.3,
 2.51,
 1.17,
 1.02,
 4.1,
 1.17,
 1.61,
 6.0,
 2.74,
 1.67,
 5.5,
 1.41,
 1.13,
 1.0,
 1.49,
 2.3,
 1.31,
 1.18,
 6.0,
 6.0,
 3.16,
 4.08,
 6

In [16]:
matriz2 = matriz(60, array3)
matriz2

array([[6.  , 5.63, 1.21, 6.  , 3.45, 1.8 , 1.  , 2.15, 1.59, 1.6 ],
       [2.02, 4.44, 1.26, 2.47, 1.07, 5.07, 1.08, 1.54, 1.55, 1.06],
       [2.02, 3.91, 1.01, 6.  , 6.  , 6.  , 3.69, 1.06, 1.21, 1.05],
       [1.54, 6.  , 1.21, 1.52, 1.19, 2.43, 1.32, 1.35, 1.7 , 1.01],
       [2.2 , 2.44, 3.08, 1.5 , 1.05, 6.  , 6.  , 1.14, 1.66, 1.08],
       [1.51, 1.43, 2.7 , 2.36, 1.67, 1.97, 1.42, 2.66, 4.99, 1.67],
       [6.  , 1.83, 2.3 , 1.  , 1.1 , 6.  , 1.  , 2.07, 1.02, 1.96],
       [3.89, 1.31, 2.51, 6.  , 6.  , 6.  , 4.26, 1.37, 1.73, 5.43],
       [1.02, 1.61, 1.17, 1.87, 1.02, 3.93, 1.37, 3.49, 1.19, 1.21],
       [1.48, 1.73, 1.02, 2.11, 1.53, 1.57, 4.83, 1.09, 2.93, 1.11],
       [1.25, 1.4 , 4.1 , 5.53, 2.38, 1.31, 1.65, 5.71, 1.35, 6.  ],
       [1.07, 2.12, 1.17, 1.46, 1.38, 5.01, 1.36, 1.85, 1.07, 2.13],
       [1.93, 1.49, 1.61, 1.14, 1.28, 3.79, 6.  , 6.  , 2.48, 1.04],
       [4.33, 5.97, 6.  , 6.  , 5.21, 1.34, 6.  , 1.5 , 1.12, 2.98],
       [3.59, 1.12, 2.74, 1.  , 6.

In [20]:
matriz3 = matriz(60,array4)
matriz3

array([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0,

In [27]:
array5 = []
for i in range(len(array4) - 1):
    if i >= 59:
        order = sum(array4[i - 59: i])
        array5.append(order)
array5

[15,
 14,
 15,
 16,
 17,
 18,
 18,
 17,
 16,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 14,
 14,
 14,
 14,
 13,
 13,
 12,
 11,
 12,
 12,
 12,
 13,
 13,
 13,
 12,
 13,
 13,
 13,
 12,
 12,
 13,
 13,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 12,
 12,
 12,
 13,
 14,
 15,
 15,
 15,
 15,
 16,
 16,
 15,
 16,
 16,
 17,
 17,
 16,
 15,
 14,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 14,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 15,
 15,
 15,
 15,
 16,
 17,
 18,
 18,
 19,
 20,
 20,
 21,
 21,
 21,
 20,
 21,
 21,
 21,
 22,
 22,
 21,
 21,
 21,
 21,
 20,
 20,
 20,
 21,
 22,
 23,
 23,
 23,
 24,
 24,
 25,
 25,
 25,
 25,
 26,
 27,
 27,
 28,
 27,
 27,
 27,
 27,
 28,
 28,
 27,
 28,
 28,
 27,
 28,
 28,
 27,
 27,
 28,
 28,
 29,
 30,
 30,
 30,
 29,
 28,
 27,
 26,
 25,
 25,
 24,
 25,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 24,
 24,
 23,
 22,
 21,
 20,
 20,
 19,
 18,
 17,
 16,
 16,
 16,
 16,
 15,
 16,
 15,
 16,
 16,
 16,
 16,
 15,
 16,
 16,
 15,
 15,
 15,
 14,
 15,
 16,
 16,
 15,
 16,


In [30]:
matriz4 = matriz(60, array5)
matriz4

array([[15, 17, 25, 16, 19, 18, 23, 18, 13],
       [14, 16, 26, 15, 18, 18, 23, 19, 13],
       [15, 15, 27, 16, 18, 17, 23, 19, 13],
       [16, 14, 27, 15, 18, 16, 22, 19, 13],
       [17, 13, 28, 16, 19, 17, 22, 19, 13],
       [18, 13, 27, 16, 19, 16, 21, 19, 13],
       [18, 14, 27, 16, 20, 17, 21, 19, 12],
       [17, 14, 27, 16, 20, 16, 21, 20, 12],
       [16, 14, 27, 15, 20, 15, 20, 20, 12],
       [16, 14, 28, 16, 21, 15, 20, 19, 13],
       [16, 14, 28, 16, 22, 15, 20, 19, 13],
       [16, 14, 27, 15, 22, 16, 20, 18, 13],
       [16, 15, 28, 15, 22, 15, 21, 18, 14],
       [16, 15, 28, 15, 23, 14, 20, 17, 14],
       [15, 14, 27, 14, 23, 15, 20, 17, 14],
       [15, 15, 28, 15, 22, 15, 19, 17, 14],
       [14, 15, 28, 16, 23, 16, 19, 17, 14],
       [14, 15, 27, 16, 23, 16, 19, 17, 13],
       [14, 16, 27, 15, 22, 16, 18, 17, 13],
       [14, 16, 28, 16, 22, 17, 19, 17, 13],
       [13, 16, 28, 15, 22, 16, 19, 16, 13],
       [13, 16, 29, 14, 23, 16, 19, 16, 13],
       [12

## Indicador de futura função:
import numpy as np

def calculate_means(array4):
    """
    Calcula a média dos elementos de array4 em janelas deslizantes de 59 elementos.

    Args:
        array4 (list): Lista de inteiros (0 ou 1).

    Returns:
        list: Lista com a média dos elementos em janelas de 59 elementos.
    """
    array6 = []
    array7 = []
    for i in range(len(array4) - 1):
        array6.append(array4[i])
        if i >= 59:
            order = float(np.mean(array6))
            array7.append(order)
    return array7

# Exemplo de uso:
# array4 = [0, 1, 0, 1, ...]  # Supondo que array4 tenha elementos suficientes
# array7 = calculate_means(array4)

# Teste unitário básico
def test_calculate_means():
    array4 = [1] * 60  # Lista com 60 elementos, todos iguais a 1
    expected_output = [1.0]  # A média dos primeiros 59 elementos é 1.0
    array7 = calculate_means(array4)
    assert array7 == expected_output, "Teste falhou!"

# Executar o teste
test_calculate_means()

In [34]:
array6 = []
array7 = []
for i in range(len(array4) - 1):
    array6.append(array4[i])
    if i >= 59:
        order = float(np.mean(array6))
        array7.append(order)

array7


[0.25,
 0.26229508196721313,
 0.27419354838709675,
 0.2857142857142857,
 0.296875,
 0.2923076923076923,
 0.2878787878787879,
 0.2835820895522388,
 0.27941176470588236,
 0.2753623188405797,
 0.2714285714285714,
 0.2676056338028169,
 0.2638888888888889,
 0.2602739726027397,
 0.2702702702702703,
 0.26666666666666666,
 0.2631578947368421,
 0.2597402597402597,
 0.2564102564102564,
 0.25316455696202533,
 0.25,
 0.24691358024691357,
 0.24390243902439024,
 0.25301204819277107,
 0.25,
 0.24705882352941178,
 0.2558139534883721,
 0.25287356321839083,
 0.25,
 0.24719101123595505,
 0.25555555555555554,
 0.25274725274725274,
 0.25,
 0.24731182795698925,
 0.24468085106382978,
 0.25263157894736843,
 0.25,
 0.25773195876288657,
 0.25510204081632654,
 0.25252525252525254,
 0.25,
 0.24752475247524752,
 0.24509803921568626,
 0.2524271844660194,
 0.25,
 0.24761904761904763,
 0.24528301886792453,
 0.2523364485981308,
 0.25925925925925924,
 0.26605504587155965,
 0.2636363636363636,
 0.26126126126126126,
 0.2

In [37]:
matriz5 = matriz(60, array7)
matriz5

array([[0.25      , 0.26666667, 0.32222222, 0.30833333, 0.31      ,
        0.30833333, 0.31904762, 0.31875   , 0.30740741],
       [0.26229508, 0.26446281, 0.32596685, 0.31120332, 0.3089701 ,
        0.30747922, 0.31828979, 0.31808732, 0.30683919],
       [0.27419355, 0.26229508, 0.32417582, 0.30991736, 0.31125828,
        0.30662983, 0.31753555, 0.31742739, 0.30627306],
       [0.28571429, 0.2601626 , 0.32786885, 0.3127572 , 0.31353135,
        0.30853994, 0.31678487, 0.31677019, 0.30570902],
       [0.296875  , 0.25806452, 0.32608696, 0.31147541, 0.3125    ,
        0.30769231, 0.31603774, 0.3161157 , 0.30514706],
       [0.29230769, 0.264     , 0.32432432, 0.31020408, 0.3147541 ,
        0.30958904, 0.31529412, 0.31546392, 0.30458716],
       [0.28787879, 0.26190476, 0.32258065, 0.30894309, 0.31372549,
        0.30874317, 0.31455399, 0.31687243, 0.3040293 ],
       [0.28358209, 0.25984252, 0.32085561, 0.30769231, 0.31596091,
        0.30790191, 0.31381733, 0.31622177, 0.30347349],


In [38]:
matriz2.shape, matriz3.shape, matriz4.shape, matriz5.shape

((60, 10), (60, 10), (60, 9), (60, 9))

In [40]:
matrizfloat = matriz2[:,1:]
matrizint = matriz3[:,1:]

In [43]:
matrizfloat.shape, matrizint.shape, matriz4.shape, matriz5.shape

((60, 9), (60, 9), (60, 9), (60, 9))

In [47]:
len(array2), len(array3), len(array4), len(array5), len(array7)

(1672, 600, 600, 540, 540)

In [59]:
x1 = matrizfloat[:,:(matrizfloat.shape[1] - 1)]
x2 = matriz4[:,:(matriz4.shape[1] - 1)]
x3 = matriz5[:,:(matriz5.shape[1] - 1)]

y = matrizint[:,-1]

In [60]:
# Empilhar as matrizes para ter um eixo extra (60, 8, 3)
X_stack = np.stack([x1, x2, x3], axis=2)  # Formato (60, 8, 3)

# Reorganizar para intercalar coluna por coluna
X_intercalado = X_stack.reshape(60, -1)  # Agora está no formato (60, 24)

print(X_intercalado.shape)  # Saída: (60, 24)

(60, 24)


In [53]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

X = X_intercalado

# Dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo XGBoost
model = xgb.XGBClassifier(
    objective='multi:softmax',  # Classificação multiclasse
    num_class=2,  # Número de categorias na saída
    eval_metric='mlogloss',
    learning_rate=0.01,
    n_estimators=100,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

# Fazer previsões
y_pred = model.predict(X_test)

# Avaliar o modelo
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f'Acurácia do modelo: {accuracy:.4f}')
print(f'F1-Score do modelo: {f1:.4f}')


Acurácia do modelo: 0.5000
F1-Score do modelo: 0.4444


In [54]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.metrics import Precision, Recall
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
import tensorflow_addons as tfa
#activation = tf.keras.activations.elu
from tensorflow.keras.optimizers import Nadam

import skfuzzy as fuzz

# Libs
import time
import warnings

2025-03-02 12:38:14.693946: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-02 12:38:14.877703: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-02 12:38:14.991632: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1740933495.144493   24559 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740933495.182876   24559 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-02 12:38:15.557656: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [84]:
def reden(array1, array3, m, n):
    print(m, n)

    # Dividindo os dados em treino e teste
    X = np.array(array3).astype("float32")  # Certificar que X está no formato correto
    y = np.array(array1)

    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Ajustando dimensões corretamente
    print("Shape inicial de x_train:", x_train.shape)  # Deve ser (48, 24, 1)

    input_shape = (n, 1)  # Usando n diretamente

    # Verificar os valores de y_train antes da conversão
    print("Valores únicos em y_train antes da conversão:", np.unique(y_train))

    # Se necessário, garantir que y_train só tenha 0 e 1
    y_train = np.where(y_train > 0, 1, 0)
    y_test = np.where(y_test > 0, 1, 0)

    # Converter para categórico
    num_classes = 2
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    print("Shape de y_train após conversão:", y_train.shape)  # Deve ser (48, 2)
    print("Shape de x_train após conversão:", x_train.shape)  # Deve ser (48, 24, 1)

    # Definição do modelo
    model = keras.Sequential([
        keras.Input(shape=input_shape),
        layers.Flatten(),
        layers.Dense(128, activation="relu", use_bias=True),
        layers.Dropout(0.5),
        layers.Dense(64, activation="relu", use_bias=True),
        layers.Dense(32, activation=tf.keras.activations.swish, use_bias=True),
        layers.Dense(num_classes, activation="softmax"),
    ])

    model.compile(
        loss=tfa.losses.SigmoidFocalCrossEntropy(alpha=0.25, gamma=2.0),
        optimizer=tf.keras.optimizers.AdamW(learning_rate=0.001, weight_decay=1e-4),
        metrics=['accuracy', Precision(name="precision"), Recall(name="recall")]
    )

    # Treinamento
    batch_size = 2**10
    epochs = 50
    model.fit(
        x_train, y_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_split=0.2
    )

    # Avaliação
    score = model.evaluate(x_test, y_test, verbose=0)
    print(f"Test loss: {score[0]:.4f}")
    print(f"Test accuracy: {score[1]:.4f}")
    print(f"Precision: {score[2]:.4f}")
    print(f"Recall: {score[3]:.4f}")

    return model


In [62]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [65]:
X.shape

(60, 24)

In [70]:
np.unique(y)

array([0, 1])

In [85]:
X = X_intercalado
model = reden(y, X, X.shape[0], X.shape[1])

60 24
Shape inicial de x_train: (48, 24)
Valores únicos em y_train antes da conversão: [0 1]
Shape de y_train após conversão: (48, 2)
Shape de x_train após conversão: (48, 24)
Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.8684 - loss: 0.9758 - precision: 0.8684 - recall: 0.8684 - val_accuracy: 0.6000 - val_loss: 1.5366 - val_precision: 0.6000 - val_recall: 0.6000
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.8421 - loss: 1.1782 - precision: 0.8421 - recall: 0.8421 - val_accuracy: 0.6000 - val_loss: 0.6279 - val_precision: 0.6000 - val_recall: 0.6000
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7895 - loss: 1.1674 - precision: 0.7895 - recall: 0.7895 - val_accuracy: 0.7000 - val_loss: 0.1801 - val_precision: 0.7000 - val_recall: 0.7000
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6316 - loss: 1.0721 - precision: 0.6316 - recall: 0.6316 - val_accuracy: 0.3000 - val_loss: 0.2713 - val_precision: 0.3000 - val_recall: 0.300