# Funções Utilizadas em Nile

Aqui devemos organizar um manual das funções utilizadas. Inicialmente, devemos pontuar, dados estudos iniciais(2 ~ 3 anos) historicamente podemos evoluir o modelo para predição de números acima de mil.

Ou seja, um trabalho de formiga ...

## Ao leitores

Procure os históricos dos commits, pondemos organizar esse projeto desde o inicio. 

Sujeito a Copy Right.

In [2]:
import numpy as np

In [16]:
def matriz_divisora(num_linhas, array):
    """
    Transforma um array unidimensional em uma matriz organizada por colunas.
    
    Args:
        array (list ou np.array): Lista de números a serem organizados.
        num_linhas (int): Número de linhas desejadas na matriz.

    Returns:
        np.array: Matriz ordenada.
    """
    
    # Reshape para matriz (por linha) e depois transpõe para organizar por colunas
    matriz = np.array(array).reshape(-1, num_linhas).T
    
    return matriz # Retorna como lista para melhor legibilidade

In [17]:
array = np.arange(300)

matriz_teste = matriz_divisora(60,array)

In [18]:
matriz_teste

array([[  0,  60, 120, 180, 240],
       [  1,  61, 121, 181, 241],
       [  2,  62, 122, 182, 242],
       [  3,  63, 123, 183, 243],
       [  4,  64, 124, 184, 244],
       [  5,  65, 125, 185, 245],
       [  6,  66, 126, 186, 246],
       [  7,  67, 127, 187, 247],
       [  8,  68, 128, 188, 248],
       [  9,  69, 129, 189, 249],
       [ 10,  70, 130, 190, 250],
       [ 11,  71, 131, 191, 251],
       [ 12,  72, 132, 192, 252],
       [ 13,  73, 133, 193, 253],
       [ 14,  74, 134, 194, 254],
       [ 15,  75, 135, 195, 255],
       [ 16,  76, 136, 196, 256],
       [ 17,  77, 137, 197, 257],
       [ 18,  78, 138, 198, 258],
       [ 19,  79, 139, 199, 259],
       [ 20,  80, 140, 200, 260],
       [ 21,  81, 141, 201, 261],
       [ 22,  82, 142, 202, 262],
       [ 23,  83, 143, 203, 263],
       [ 24,  84, 144, 204, 264],
       [ 25,  85, 145, 205, 265],
       [ 26,  86, 146, 206, 266],
       [ 27,  87, 147, 207, 267],
       [ 28,  88, 148, 208, 268],
       [ 29,  

In [19]:
matriz_teste.shape

(60, 5)

In [20]:
def matriz_historica(qt_colunas, array):
    """
    Gera uma matriz sequencial a partir de um array, com o número de colunas especificado.

    Args:
        array (list ou np.ndarray): Array de entrada.
        qt_colunas (int): Número de colunas desejado na matriz.

    Returns:
        np.ndarray: Matriz sequencial.
    """
    if qt_colunas > len(array):
        raise ValueError("O número de colunas não pode ser maior que o tamanho do array.")

    # Número de linhas na matriz
    num_linhas = len(array) - qt_colunas + 1

    # Criando a matriz sequencial
    matriz = np.array([array[i:i + qt_colunas] for i in range(num_linhas)])
    return matriz


In [21]:
array = np.arange(300)

matriz_teste = matriz_historica(240,array)

In [22]:
matriz_teste

array([[  0,   1,   2, ..., 237, 238, 239],
       [  1,   2,   3, ..., 238, 239, 240],
       [  2,   3,   4, ..., 239, 240, 241],
       ...,
       [ 58,  59,  60, ..., 295, 296, 297],
       [ 59,  60,  61, ..., 296, 297, 298],
       [ 60,  61,  62, ..., 297, 298, 299]])

In [23]:
matriz_teste.shape

(61, 240)

In [24]:
def media_historica(array):
    """
    Função que organiza o histórico das médias das últimas 60 entradas.
    Args:
        array (list ou np.ndarray): Array de entrada.
    Returns:
        np.ndarray: Array das médias sequenciais.
    """
    array = np.asarray(array)  # Garante que a entrada seja um np.ndarray
    if len(array) < 60:
        raise ValueError("O array deve ter pelo menos 60 elementos para calcular a média histórica.")
    
    # Calcula a média móvel com janela de 60
    medias = np.convolve(array, np.ones(60) / 60, mode='valid')
    
    return medias

In [25]:
array = np.arange(300)

array_teste = media_historica(array)

In [26]:
array_teste

array([ 29.5,  30.5,  31.5,  32.5,  33.5,  34.5,  35.5,  36.5,  37.5,
        38.5,  39.5,  40.5,  41.5,  42.5,  43.5,  44.5,  45.5,  46.5,
        47.5,  48.5,  49.5,  50.5,  51.5,  52.5,  53.5,  54.5,  55.5,
        56.5,  57.5,  58.5,  59.5,  60.5,  61.5,  62.5,  63.5,  64.5,
        65.5,  66.5,  67.5,  68.5,  69.5,  70.5,  71.5,  72.5,  73.5,
        74.5,  75.5,  76.5,  77.5,  78.5,  79.5,  80.5,  81.5,  82.5,
        83.5,  84.5,  85.5,  86.5,  87.5,  88.5,  89.5,  90.5,  91.5,
        92.5,  93.5,  94.5,  95.5,  96.5,  97.5,  98.5,  99.5, 100.5,
       101.5, 102.5, 103.5, 104.5, 105.5, 106.5, 107.5, 108.5, 109.5,
       110.5, 111.5, 112.5, 113.5, 114.5, 115.5, 116.5, 117.5, 118.5,
       119.5, 120.5, 121.5, 122.5, 123.5, 124.5, 125.5, 126.5, 127.5,
       128.5, 129.5, 130.5, 131.5, 132.5, 133.5, 134.5, 135.5, 136.5,
       137.5, 138.5, 139.5, 140.5, 141.5, 142.5, 143.5, 144.5, 145.5,
       146.5, 147.5, 148.5, 149.5, 150.5, 151.5, 152.5, 153.5, 154.5,
       155.5, 156.5,

In [27]:
array_teste.shape

(241,)

In [28]:
import numpy as np

def resize_and_merge_matrices(matrix1, matrix2, fill_value=0):
    """
    Redimensiona e combina duas matrizes em uma única matriz quadrada convexa.
    
    Parâmetros:
        matrix1 (np.array): Primeira matriz.
        matrix2 (np.array): Segunda matriz.
        fill_value (float, opcional): Valor para preenchimento ao redimensionar. Padrão é 0.
    
    Retorna:
        np.array: Matriz quadrada convexa combinada.
    """
    # Determinar os tamanhos máximos das matrizes
    max_rows = max(matrix1.shape[0], matrix2.shape[0])
    max_cols = max(matrix1.shape[1], matrix2.shape[1])
    
    # Definir o tamanho mínimo necessário para tornar a matriz quadrada
    square_size = max(max_rows, max_cols)
    
    # Função para redimensionar uma matriz para um tamanho quadrado
    def resize_matrix(matrix, size, fill_value):
        resized = np.full((size, size), fill_value, dtype=matrix.dtype)
        resized[:matrix.shape[0], :matrix.shape[1]] = matrix  # Mantém os valores originais no canto superior esquerdo
        return resized
    
    # Redimensionar as duas matrizes
    resized_matrix1 = resize_matrix(matrix1, square_size, fill_value)
    resized_matrix2 = resize_matrix(matrix2, square_size, fill_value)
    
    # Criar a matriz convexa combinando as duas
    combined_matrix = np.maximum(resized_matrix1, resized_matrix2)
    
    return combined_matrix

# Exemplo de uso
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6, 7], [8, 9, 10]])

result = resize_and_merge_matrices(mat1, mat2)
print(result)


[[ 5  6  7]
 [ 8  9 10]
 [ 0  0  0]]


In [ ]:
global_saved_arrays = []  # Lista global para armazenar os arrays

def save_merged_array(X):
    """
    Salva a matriz X em um array global.
    """
    global global_saved_arrays
    global_saved_arrays.append(X)
    print("Matriz salva com sucesso! Total de matrizes armazenadas:", len(global_saved_arrays))
    
# Exemplo de uso:
# X = resize_and_merge_matrices(array2, array3)
# save_merged_array(X)