# Aleatoriedade - 21.03.25
---

## Objetivo Geral
Trabalhar com sequências aleatórias e testar seu grau de aleatoriedade pela entropia de sequências aleatórias.

---

### Teste 1

In [3]:
import pandas as pd
import numpy as np

In [4]:
#Função que trata array em uma matriz sequencial
def matriz(num_colunas, array1):
    """
    Gera uma matriz sequencial a partir de um array, com o número de colunas especificado.

    Args:
        array (list ou np.ndarray): Array de entrada.
        num_colunas (int): Número de colunas desejado na matriz.

    Returns:
        np.ndarray: Matriz sequencial.
    """
    if num_colunas > len(array1):
        raise ValueError("O número de colunas não pode ser maior que o tamanho do array.")

    # Número de linhas na matriz
    num_linhas = len(array1) - num_colunas + 1

    # Criando a matriz sequencial
    matriz = np.array([array1[i:i + num_colunas] for i in range(num_linhas)])
    return matriz

In [5]:
array = np.arange(300)

array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
matriz1 = matriz(30,array)
matriz1

array([[  0,   1,   2, ...,  27,  28,  29],
       [  1,   2,   3, ...,  28,  29,  30],
       [  2,   3,   4, ...,  29,  30,  31],
       ...,
       [268, 269, 270, ..., 295, 296, 297],
       [269, 270, 271, ..., 296, 297, 298],
       [270, 271, 272, ..., 297, 298, 299]], shape=(271, 30))

In [8]:
data1 = pd.read_csv("/home/darkcover1/Documentos/Work/Out/dados/odds_200k.csv")
data1.head

<bound method NDFrame.head of         Unnamed: 0    Odd  Odd_Categoria  odd_entrada
0                0   3.85              9         11.0
1                1   6.96             10          9.0
2                2   5.41             10         10.0
3                3   1.05              2         10.0
4                4   1.70              6          2.0
...            ...    ...            ...          ...
199994      199994   1.62              5         11.0
199995      199995   2.61              8          5.0
199996      199996  14.20             11          8.0
199997      199997   4.11              9         11.0
199998      199998   3.36              8          9.0

[199999 rows x 4 columns]>

In [9]:
array1 = []
for i in range(0, 1200):
    numero_odd = data1['Odd'][i]
    if numero_odd >= 3:
        array1.append(1)
    else:
        array1.append(0)

In [13]:
matriz_zeroum = matriz(120,array1)
matriz_zeroum

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 1, 0, ..., 0, 1, 1]], shape=(1081, 120))

In [14]:
import numpy as np
from collections import Counter
import math

def calcular_entropia(array):
    # Conta a frequência de cada elemento no array
    contador = Counter(array)
    total_elementos = len(array)
    
    # Calcula a entropia
    entropia = 0.0
    for count in contador.values():
        probabilidade = count / total_elementos
        if probabilidade > 0:  # Evita log(0)
            entropia -= probabilidade * math.log2(probabilidade)
    
    return entropia

def eh_sequencia_aleatoria_binaria(array, limiar=0.9):
    # Verifica se o array contém apenas 0s e 1s
    if not all(x in {0, 1} for x in array):
        raise ValueError("O array deve conter apenas 0s e 1s.")
    
    # Calcula a entropia do array
    entropia = calcular_entropia(array)
    
    # Para um array binário, a entropia máxima é 1
    entropia_maxima = 1.0
    
    # Normaliza a entropia (neste caso, a entropia já está normalizada)
    entropia_normalizada = entropia / entropia_maxima
    
    # Determina se a entropia normalizada está acima do limiar
    return entropia_normalizada >= limiar

# Exemplo de uso
array_aleatorio = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
print(eh_sequencia_aleatoria_binaria(array_aleatorio))  # Deve retornar True

array_nao_aleatorio = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
print(eh_sequencia_aleatoria_binaria(array_nao_aleatorio))  # Deve retornar False

True
False


In [15]:
contador = 0
    
for i in range(0, matriz_zeroum.shape[0]):
    condicao1 = eh_sequencia_aleatoria_binaria(matriz_zeroum[i,:])
    if condicao1 is False:
        contador += 1
        print(eh_sequencia_aleatoria_binaria(matriz_zeroum[i,:]), i)
print(contador)

False 439
False 440
False 441
False 468
False 469
False 592
False 593
False 837
False 850
False 851
False 852
False 853
False 854
False 855
False 856
False 857
False 858
False 859
False 860
False 861
False 862
False 863
False 864
False 865
False 866
False 867
False 868
False 869
False 870
False 871
False 872
False 873
False 874
False 875
False 876
False 877
False 878
False 879
False 880
False 881
False 882
False 883
False 884
False 885
False 886
False 887
False 888
False 889
False 890
False 891
False 892
False 893
False 894
False 895
False 896
False 897
False 898
False 899
False 900
False 901
False 902
False 903
False 904
False 905
False 906
False 907
False 908
False 909
False 910
False 911
False 912
False 913
False 914
False 915
False 916
False 917
False 918
False 919
False 920
False 921
False 922
False 923
False 924
False 925
False 926
False 927
False 928
False 929
False 930
False 931
False 932
False 933
False 934
False 935
False 936
False 937
False 938
False 939
False 940
False 941
